version: "3.7"

services:
  node:
    build: .
    container_name: portfolio.njk.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cavity.rule=Host(`portfolio.njk.localhost`)"
      - "traefik.http.routers.cavity.tls=true"
      - "traefik.docker.network=proxy"
    volumes:
      - .:/app
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true